from DQM import DQM_multiple_file, DQM_single_file
from load_data import *


if __name__ == '__main__':
    """dqm_obj = DQM()
    dqm_obj.set_input_path('/home/lin/Documents/CAMH/SenseActivity/data/Test')
    dqm_obj.set_APD(True)
    dqm_obj.set_MDR(True)
    dqm_obj.set_RLC(True)
    dqm_obj.set_SCR(True)
    dqm_obj.set_SNR(True)
    dqm_obj.set_SRC(True)
    dqm_obj.set_VRC(True)
    dqm_obj.compute_DQM()
    print(dqm_obj.get_DQM())
    print(dqm_obj.get_IRLR())
    print(dqm_obj.get_RLC())
    print(dqm_obj.get_SNR())
    print(dqm_obj.get_VRC())
    print(dqm_obj.get_SCR())
    print(dqm_obj.get_SRC())
    print(dqm_obj.get_MDR())
    print(dqm_obj.get_APD())"""
    #dqm_obj.save_to_file('/home/lin/Documents/CAMH/SenseActivity/data/result_extreme.csv')
    single_file_dqm = DQM_single_file()
    df = load_data_pd_single_file('/home/lin/Documents/CAMH/SenseActivity/data/Test/SUBJ00001/Accelerometer/SUBJ00001_Accelerometer_REC000000.json')
    single_file_dqm.set_input_record(df)
    #single_file_dqm.set_MDR(False)
    single_file_dqm.compute_DQM()
    print(single_file_dqm.get_fields())
    print(single_file_dqm.get_DQM())
    single_csv_file_dqm = DQM_single_file()
    df = load_data_csv_one_file('/home/lin/Documents/CAMH/SenseActivity/data/csv_data/id9603e9c3.csv')
    single_csv_file_dqm.set_input_record(df)
    single_csv_file_dqm.compute_DQM()
    print(single_csv_file_dqm.get_DQM())
    multi_file_dqm = DQM_multiple_file()
    df_list = load_data_pd_multi_file('/home/lin/Documents/CAMH/SenseActivity/data/Test/SUBJ00001/Accelerometer')
    multi_file_dqm.set_input_data(df_list)
    multi_file_dqm.compute_DQM()
    print(multi_file_dqm.get_fields())
    print(multi_file_dqm.get_DQM())
    multi_csvfile_dqm = DQM_multiple_file()
    df_list = load_data_csv_multi_file('/home/lin/Documents/CAMH/SenseActivity/data/csv_data')
    multi_csvfile_dqm.set_input_data(df_list)
    multi_csvfile_dqm.compute_DQM()
    print(multi_csvfile_dqm.get_fields())
    print(multi_csvfile_dqm.get_DQM())
